// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlnlbdrlruuoffnyaltc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbmxiZHJscnV1b2ZmbnlhbHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzA4MzUsImV4cCI6MjA2MzY0NjgzNX0.24LD3CVvwmgnj-_SLCGX4jpyc3PnKn_klSjrDfS6Bqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);